# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Prodo-iOS' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

pod 'TBEmptyDataSet'
pod 'AlertOnboarding'
pod 'Firebase/Core'
pod 'Firebase/Storage'


  # Pods for Prodo-iOS

  target 'Prodo-iOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Prodo-iOSUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
